In [6]:
import numpy as np
from random import *

scal = 2.3

print(scal)
print(type(scal))

scal = '2.3'
print(scal)
print(np.isscalar(scal))

del scal

print("#================================================")

vect = np.arange(1,10,1)

print(vect)
print(type(vect))

vect = np.append(vect, 10)
print(vect)

vect = np.delete(vect, vect[1])
print(vect)
del vect

print("#================================================")

matrix = []

print(matrix)

maxrixSize = int(input('Matrix size'))
while len(matrix) != maxrixSize:
    value = randint(1,10)
    matrix.append(value)
print(matrix)

matrix.pop(len(matrix)-1)
print(matrix)


2.3
<class 'float'>
2.3
True
#================================================
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  4  5  6  7  8  9 10]
#================================================
[]
[8, 3, 2, 9, 10, 4, 7, 5, 9, 3]
[8, 3, 2, 9, 10, 4, 7, 5, 9]
